version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build: .
    ports:
      - '4000:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=graphql-training
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - NODE_ENV=production
      - PORT=8000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: graphql-training
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}